# Generated by Django 4.2 on 2023-10-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_to_dating",
                    models.CharField(
                        choices=[
                            ("Males", "Males"),
                            ("Females", "Females"),
                            ("Non-binary Individuals", "Non-binary Individuals"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
