# Generated by Django 4.2 on 2023-10-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Non-binary")],
                default="Not Specified",
                max_length=20,
            ),
        ),
    ]
