# Generated by Django 4.2 on 2023-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingpreference",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Males"),
                    ("F", "Females"),
                    ("N", "Non-binary Individuals"),
                    ("NS", "Not Specified"),
                ],
                max_length=25,
            ),
        ),
    ]
