# Generated by Django 4.2 on 2023-10-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_pronoun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
