# Generated by Django 4.2 on 2023-11-05 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("reaction", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("character_creation", "Character Creation"),
                            ("regular_turn", "Regular Turn"),
                            ("inactive", "Inactive"),
                            ("ended", "Ended"),
                        ],
                        default="initializing",
                        max_length=50,
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        default="c0f30671-9e7a-4ce9-b5d5-dfdc4665742c",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chat_messages",
                    models.ManyToManyField(blank=True, to="game.chatmessage"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.IntegerField(default=1)),
                ("player_a_completed_cycle", models.BooleanField(default=False)),
                ("player_b_completed_cycle", models.BooleanField(default=False)),
                ("player_a_narrative_choice_made", models.BooleanField(default=False)),
                ("player_b_narrative_choice_made", models.BooleanField(default=False)),
                (
                    "player_a_moon_phase_message_written",
                    models.BooleanField(default=False),
                ),
                (
                    "player_b_moon_phase_message_written",
                    models.BooleanField(default=False),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("select_question", "Select Question"),
                            ("answer_question", "Answer Question"),
                            ("react_emoji", "React with Emoji"),
                            ("narrative_choices", "Narrative Choices"),
                            ("moon_phase", "Moon Phase"),
                        ],
                        default="select_question",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_players",
                        to="game.gamesession",
                    ),
                ),
                (
                    "question_pool",
                    models.ManyToManyField(blank=True, to="game.question"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("word_pool", models.ManyToManyField(blank=True, to="game.word")),
            ],
        ),
        migrations.CreateModel(
            name="NarrativeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gamesession",
                    ),
                ),
                (
                    "game_turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.gameturn"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameturn",
            name="active_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="current_game_turn",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_game",
                to="game.gameturn",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="playerA",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player1_sessions",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="playerB",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player2_sessions",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="game_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.gamesession"
            ),
        ),
    ]
