# Generated by Django 4.2 on 2023-11-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoonSignInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_quarter", models.CharField(max_length=150)),
                ("first_quarter_reason", models.TextField()),
                ("full_moon", models.CharField(max_length=150)),
                ("full_moon_reason", models.TextField()),
                ("last_quarter", models.CharField(max_length=150)),
                ("last_quarter_reason", models.TextField()),
                ("new_moon", models.CharField(max_length=150)),
                ("new_moon_reason", models.TextField()),
            ],
        ),
    ]
