# Generated by Django 4.2 on 2023-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameturn",
            name="game_session",
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="7ed51e5f-0e39-4936-b693-d355e111b321",
                max_length=255,
                unique=True,
            ),
        ),
    ]
