# Generated by Django 4.2 on 2023-11-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="asked_questions",
            field=models.ManyToManyField(blank=True, to="game.question"),
        ),
    ]
