# Generated by Django 4.2 on 2023-11-26 00:17

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoonSignInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_quarter", models.CharField(max_length=150)),
                ("first_quarter_reason", models.TextField()),
                ("full_moon", models.CharField(max_length=150)),
                ("full_moon_reason", models.TextField()),
                ("last_quarter", models.CharField(max_length=150)),
                ("last_quarter_reason", models.TextField()),
                ("new_moon", models.CharField(max_length=150)),
                ("new_moon_reason", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("initializing", "Initializing"),
                    ("character_creation", "Character Creation"),
                    ("moon_sign_interpretation", "Moon Sign Interpretation"),
                    ("regular_turn", "Regular Turn"),
                    ("inactive", "Inactive"),
                    ("ended", "Ended"),
                ],
                default="initializing",
                max_length=50,
            ),
        ),
    ]
