# Generated by Django 4.2 on 2023-11-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_remove_gameturn_game_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="2172913d-7dec-455e-b5c1-17a060fcdb97",
                max_length=255,
                unique=True,
            ),
        ),
    ]
