# Generated by Django 4.2.6 on 2023-11-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_gamesession_asked_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="game_session",
        ),
        migrations.RemoveField(
            model_name="gamesession",
            name="chat_messages",
        ),
        migrations.CreateModel(
            name="GameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_messages",
                    models.ManyToManyField(
                        blank=True, related_name="game_log", to="game.chatmessage"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="gameLog",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_game",
                to="game.gamelog",
            ),
        ),
    ]
