# Generated by Django 4.2 on 2023-11-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_moonsigninterpretation_on_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="MoonSignInterpretation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.moonsigninterpretation",
            ),
        ),
    ]
