# Generated by Django 4.2 on 2023-11-25 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_publicprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicprofile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="name",
        ),
    ]
