# Generated by Django 4.2 on 2023-11-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="3a1110df-cc06-4ecc-ac4c-4555ae2aa3ab",
                max_length=255,
                unique=True,
            ),
        ),
    ]
