# Generated by Django 4.2 on 2023-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_publicprofile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameturn",
            name="narrative_nights",
            field=models.IntegerField(default=1),
        ),
    ]
