# Generated by Django 4.2 on 2023-12-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_moonsigninterpretation_on_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_general",
            field=models.BooleanField(default=False),
        ),
    ]
