# Generated by Django 4.2 on 2023-11-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="6f7902ed-cb0c-467f-bc94-422f09d5a9ea",
                max_length=255,
                unique=True,
            ),
        ),
    ]
