# Generated by Django 4.2 on 2023-11-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.character",
            ),
        ),
    ]
