# Generated by Django 4.2 on 2023-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_narrativechoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameturn",
            name="narrative_choices_made",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
