# Generated by Django 4.2 on 2023-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_question_is_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_general",
            field=models.BooleanField(default=True),
        ),
    ]
