# Generated by Django 4.2 on 2023-11-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="989ed1ed-1090-4212-ac75-6fa35143b663",
                max_length=255,
                unique=True,
            ),
        ),
    ]
