# Generated by Django 4.2 on 2023-11-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_gameturn_narrative_choices_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameturn",
            name="moon_meanings_submitted",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
