# Generated by Django 4.2 on 2023-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_gameturn_narrative_nights"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
