# Generated by Django 4.2 on 2023-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="74ee4c1f-11dd-42de-a9c6-3cdc4370fa81",
                max_length=255,
                unique=True,
            ),
        ),
    ]
