# Generated by Django 4.2 on 2023-12-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_question_is_general"),
    ]

    operations = [
        migrations.CreateModel(
            name="moon_phase_dates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moon_phase",
                    models.CharField(
                        choices=[
                            ("new_moon", "New Moon"),
                            ("first_quarter", "First Quarter"),
                            ("full_moon", "Full Moon"),
                            ("last_quarter", "Last Quarter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="moon_phase_turn_sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_moon_turn_number", models.IntegerField(blank=True, null=True)),
                (
                    "first_quarter_turn_number",
                    models.IntegerField(blank=True, null=True),
                ),
                ("full_moon_turn_number", models.IntegerField(blank=True, null=True)),
                (
                    "last_quarter_turn_number",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameturn",
            name="moon_phase_turn_sequence",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.moon_phase_turn_sequence",
            ),
        ),
    ]
