# Generated by Django 4.2 on 2023-11-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_chatmessage_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="kind_of_word",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
