# Generated by Django 4.2 on 2023-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="87309202-0a55-4cc0-b298-3868954efa6f",
                max_length=255,
                unique=True,
            ),
        ),
    ]
