# Generated by Django 4.2 on 2023-11-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="f230c283-ae9e-4fd1-91c1-82eb4aa404e7",
                max_length=255,
                unique=True,
            ),
        ),
    ]
