# Generated by Django 4.2 on 2023-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_alter_gamesession_game_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameturn",
            name="player_a_completed_cycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gameturn",
            name="player_b_completed_cycle",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="game_id",
            field=models.CharField(
                default="0a366ea6-fe2f-4f35-84bb-e7eae80bc683",
                max_length=255,
                unique=True,
            ),
        ),
    ]
